#.github/workflows/php.yml
name: Bundle Tests

on:
  push: ~
  pull_request: ~

jobs:

  test:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '8.1', '8.2', '8.3' ]
        symfony: [ '6.0.0', '6.1.0', '6.2.0', '6.3.0', '6.4.0' ]

    steps:
      - uses: actions/checkout@master

      - name: "Cache Composer packages"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('composer.json') }}"
          restore-keys: "php-"

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        run: "composer install --prefer-dist"
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: install test tools
        run: composer bin all install

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Run Psalm
        run: ./vendor/bin/psalm

  php-cs-fixer:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Style Fixes
